deployments:
  cf.gov:
    dockerimage: centos/python-36-centos7:latest
    environment:
      - DATABASE_URL: postgres://cfpb:cfpb@postgres/cfgov
    build_options: -u 0
    build_steps:
      - whoami
      - yum update
      - yum install postgresql
      - cd /code
      - pip install -U pip
      - pip install -r requirements/local.txt
    launch_steps:
      - cd /code
      - cfgov/manage.py runserver 0.0.0.0:8000
    port_forwarding: 80:8000
