# Generated by Django 3.2.23 on 2023-12-20 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0014_update_ds_links"),
    ]

    operations = []
