# Generated by Django 4.2.11 on 2024-04-29 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0032_alter_browsepage_content"),
    ]

    run_before = [
        ("wagtailsearch", "0008_remove_query_and_querydailyhits_models"),
    ]

    operations = [
    ]
